services:
  postgres:
    container_name: spring_security_pg
    image: postgres
    environment:
      POSTGRES_USER: nayem
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-security-net
    restart: unless-stopped   #If something goes wrong(server stop), it will restart

  keycloak:
    container_name: keycloak-spring-security
    image: quay.io/keycloak/keycloak:26.1.0
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-security-net
    command:
      - "start-dev"

networks:
  spring-security-net:
    driver: bridge

volumes:
  postgres: